### ISSUE TITLE
Error in usage

### ISSUE THREAD

**Issue by jonatasnardi** [assuncaocharles/cpf-mask-ng2#1]
When I added your lib to my project, according the usage, I got this error below:

ERROR in node_modules/cpf-mask-ng2/node_modules/rxjs/Subject.d.ts(16,22): error TS2415: Class 'Subject<T>' incorrectly extends base class 'Observable<T>'.
  Types of property 'lift' are incompatible.
    Type '<R>(operator: Operator<T, R>) => Observable<T>' is not assignable to type '<R>(operator: Operator<T, R>) => Observable<R>'.
      Type 'Observable<T>' is not assignable to type 'Observable<R>'.
        Type 'T' is not assignable to type 'R'.

Angular CLI: 1.7.3
Node: 6.11.2
OS: win32 x64
Angular:

**Comment by assuncaocharles** [comment]
Hi @jonatasnardi,

Thanks for reporting. It's fixed now, can you try it again?
